# here i have deleted some unwanted feature for our better understanding nethier i have converted NAN values nor work with 0 vlaues ,then renamed some of the features and creted one more feature , and after that finded profit among revenue , budget and finds the average run time of movies which have profit more than 50 crores
1 max min profit
2 max min revenue 
3 max min budget
4 average runtime
5 max min profit,revenue,budget and average runtime over 50 crores

In [ ]:
import pandas as pd #importig libraries
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("movies.csv") #imnporting file
data.head(5) #dispalying starting 5 rows

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,...,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/15,5562,6.5,2015,1.379999e+08,1.392446e+09
1,76341,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,What a Lovely Day.,...,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/15,6185,7.1,2015,1.379999e+08,3.481613e+08
2,262500,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,One Choice Can Destroy You,...,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/15,2480,6.3,2015,1.012000e+08,2.716190e+08
3,140607,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Every generation has a story.,...,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/15,5292,7.5,2015,1.839999e+08,1.902723e+09
4,168259,tt2820852,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,Vengeance Hits Home,...,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/15,2947,7.3,2015,1.747999e+08,1.385749e+09

In [3]:
data.columns #checking columns names

Index(['id', 'imdb_id', 'popularity', 'budget', 'revenue', 'original_title',
       'cast', 'homepage', 'director', 'tagline', 'keywords', 'overview',
       'runtime', 'genres', 'production_companies', 'release_date',
       'vote_count', 'vote_average', 'release_year', 'budget_adj',
       'revenue_adj'],
      dtype='object')

In [4]:
data.shape #shape of data row*columns

(10866, 21)

In [5]:
data.isnull().values.any() #any NAN value is present or not

True

In [6]:
data.isnull().values.sum() # sum of all NAN values

13434

In [7]:
data.dtypes #types of all features

id                        int64
imdb_id                  object
popularity              float64
budget                    int64
revenue                   int64
original_title           object
cast                     object
homepage                 object
director                 object
tagline                  object
keywords                 object
overview                 object
runtime                   int64
genres                   object
production_companies     object
release_date             object
vote_count                int64
vote_average            float64
release_year              int64
budget_adj              float64
revenue_adj             float64
dtype: object

In [8]:
delcol = [ 'id', 'imdb_id', 'popularity', 'budget_adj', 'revenue_adj', 'homepage', 'keywords', 
           'overview', 'production_companies', 'vote_count', 'vote_average'] #storing all unwanted columns

data = data.drop(delcol, 1) #droping unwanted columns

data.head(5)

,budget,revenue,original_title,cast,director,tagline,runtime,genres,release_date,release_year
0,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,124,Action|Adventure|Science Fiction|Thriller,6/9/15,2015
1,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,George Miller,What a Lovely Day.,120,Action|Adventure|Science Fiction|Thriller,5/13/15,2015
2,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,Robert Schwentke,One Choice Can Destroy You,119,Adventure|Science Fiction|Thriller,3/18/15,2015
3,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,Every generation has a story.,136,Action|Adventure|Science Fiction|Fantasy,12/15/15,2015
4,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,Vengeance Hits Home,137,Action|Crime|Thriller,4/1/15,2015

In [9]:
data.rename(columns = {'original_title' : 'movie_title', 'budget' : 'budget($)', 'revenue' : 'revenue($)'}, inplace = True) #renaming few coluns for our better understanding

data.head() # result after changing the name

,budget($),revenue($),movie_title,cast,director,tagline,runtime,genres,release_date,release_year
0,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,124,Action|Adventure|Science Fiction|Thriller,6/9/15,2015
1,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,George Miller,What a Lovely Day.,120,Action|Adventure|Science Fiction|Thriller,5/13/15,2015
2,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,Robert Schwentke,One Choice Can Destroy You,119,Adventure|Science Fiction|Thriller,3/18/15,2015
3,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,Every generation has a story.,136,Action|Adventure|Science Fiction|Fantasy,12/15/15,2015
4,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,Vengeance Hits Home,137,Action|Crime|Thriller,4/1/15,2015

In [10]:
data.dtypes #checking again type of features

budget($)        int64
revenue($)       int64
movie_title     object
cast            object
director        object
tagline         object
runtime          int64
genres          object
release_date    object
release_year     int64
dtype: object

In [11]:
data['release_date'] = data['release_date'].apply(pd.to_datetime) #chnaging date time format for better understanding
data.dtypes #previous it was object now it is in date time format

budget($)                int64
revenue($)               int64
movie_title             object
cast                    object
director                object
tagline                 object
runtime                  int64
genres                  object
release_date    datetime64[ns]
release_year             int64
dtype: object

In [12]:
data.insert(2, 'profit($)', data['revenue($)'] - data['budget($)']) #creating profit column .i.e profit=revenue -budget

data.head()

,budget($),revenue($),profit($),movie_title,cast,director,tagline,runtime,genres,release_date,release_year
0,150000000,1513528810,1363528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,124,Action|Adventure|Science Fiction|Thriller,2015-06-09,2015
1,150000000,378436354,228436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,George Miller,What a Lovely Day.,120,Action|Adventure|Science Fiction|Thriller,2015-05-13,2015
2,110000000,295238201,185238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,Robert Schwentke,One Choice Can Destroy You,119,Adventure|Science Fiction|Thriller,2015-03-18,2015
3,200000000,2068178225,1868178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,Every generation has a story.,136,Action|Adventure|Science Fiction|Fantasy,2015-12-15,2015
4,190000000,1506249360,1316249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,Vengeance Hits Home,137,Action|Crime|Thriller,2015-04-01,2015

In [29]:
highp=data["profit($)"].max() #max profit
highp

2544505847

In [30]:
lowp=data["profit($)"].min()#min profit
lowp

-413912431

In [31]:
highrevenue=data["revenue($)"].max() #max revenue
highrevenue

2781505847

In [32]:
lowrevenue=data["revenue($)"].min() #min revenue
lowrevenue

0

In [33]:
highbudget=data["budget($)"].max() #max budget
highbudget

425000000

In [35]:
lowbudget=data["budget($)"].min() #min budget
lowbudget

0

In [38]:
avgruntime=data['runtime'].mean() #average runtime
avgruntime

102.07086324314375

In [42]:
profitmovies = data[data['profit($)'] > 50000000] #max profut above 50 crore 
profitmovies

,budget($),revenue($),profit($),movie_title,cast,director,tagline,runtime,genres,release_date,release_year
0,150000000,1513528810,1363528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,124,Action|Adventure|Science Fiction|Thriller,2015-06-09,2015
1,150000000,378436354,228436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,George Miller,What a Lovely Day.,120,Action|Adventure|Science Fiction|Thriller,2015-05-13,2015
2,110000000,295238201,185238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,Robert Schwentke,One Choice Can Destroy You,119,Adventure|Science Fiction|Thriller,2015-03-18,2015
3,200000000,2068178225,1868178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,Every generation has a story.,136,Action|Adventure|Science Fiction|Fantasy,2015-12-15,2015
4,190000000,1506249360,1316249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,Vengeance Hits Home,137,Action|Crime|Thriller,2015-04-01,2015
5,135000000,532950503,397950503,The Revenant,Leonardo DiCaprio|Tom Hardy|Will Poulter|Domhn...,Alejandro GonzÃƒÂ¡lez IÃƒÂ±ÃƒÂ¡rritu,"(n. One who has returned, as if from the dead.)",156,Western|Drama|Adventure|Thriller,2015-12-25,2015
6,155000000,440603537,285603537,Terminator Genisys,Arnold Schwarzenegger|Jason Clarke|Emilia Clar...,Alan Taylor,Reset the future,125,Science Fiction|Action|Thriller|Adventure,2015-06-23,2015
7,108000000,595380321,487380321,The Martian,Matt Damon|Jessica Chastain|Kristen Wiig|Jeff ...,Ridley Scott,Bring Him Home,141,Drama|Adventure|Science Fiction,2015-09-30,2015
8,74000000,1156730962,1082730962,Minions,Sandra Bullock|Jon Hamm|Michael Keaton|Allison...,Kyle Balda|Pierre Coffin,"Before Gru, they had a history of bad bosses",91,Family|Animation|Adventure|Comedy,2015-06-17,2015
9,175000000,853708609,678708609,Inside Out,Amy Poehler|Phyllis Smith|Richard Kind|Bill Ha...,Pete Docter,Meet the little voices inside your head.,94,Comedy|Animation|Family,2015-06-09,2015
10,245000000,880674609,635674609,Spectre,Daniel Craig|Christoph Waltz|LÃƒÂ©a Seydoux|Ralp...,Sam Mendes,A Plan No One Escapes,148,Action|Adventure|Crime,2015-10-26,2015
13,88000000,243637091,155637091,Pixels,Adam Sandler|Michelle Monaghan|Peter Dinklage|...,Chris Columbus,Game On.,105,Action|Comedy|Science Fiction,2015-07-16,2015
14,280000000,1405035767,1125035767,Avengers: Age of Ultron,Robert Downey Jr.|Chris Hemsworth|Mark Ruffalo...,Joss Whedon,A New Age Has Come.,141,Action|Adventure|Science Fiction,2015-04-22,2015
15,44000000,155760117,111760117,The Hateful Eight,Samuel L. Jackson|Kurt Russell|Jennifer Jason ...,Quentin Tarantino,No one comes up here without a damn good reason.,167,Crime|Drama|Mystery|Western,2015-12-25,2015
16,48000000,325771424,277771424,Taken 3,Liam Neeson|Forest Whitaker|Maggie Grace|Famke...,Olivier Megaton,It Ends Here,109,Crime|Action|Thriller,2015-01-01,2015
17,130000000,518602163,388602163,Ant-Man,Paul Rudd|Michael Douglas|Evangeline Lilly|Cor...,Peyton Reed,Heroes Don't Get Any Bigger,115,Science Fiction|Action|Adventure,2015-07-14,2015
18,95000000,542351353,447351353,Cinderella,Lily James|Cate Blanchett|Richard Madden|Helen...,Kenneth Branagh,Midnight is just the beginning.,112,Romance|Fantasy|Family|Drama,2015-03-12,2015
19,160000000,650523427,490523427,The Hunger Games: Mockingjay - Part 2,Jennifer Lawrence|Josh Hutcherson|Liam Hemswor...,Francis Lawrence,The fire will burn forever.,136,War|Adventure|Science Fiction,2015-11-18,2015
21,30000000,91709827,61709827,Southpaw,Jake Gyllenhaal|Rachel McAdams|Forest Whitaker...,Antoine Fuqua,Believe in Hope.,123,Action|Drama,2015-06-15,2015
22,110000000,470490832,360490832,San Andreas,Dwayne Johnson|Alexandra Daddario|Carla Gugino...,Brad Peyton,"A rescue pilot survived an earthquake, this is...",114,Action|Drama|Thriller,2015-05-27,2015
23,40000000,569651467,529651467,Fifty Shades of Grey,Dakota Johnson|Jamie Dornan|Jennifer Ehle|Eloi...,Sam Taylor-Johnson,Are you curious?,125,Drama|Romance,2015-02-11,2015
24,28000000,133346506,105346506,The Big Short,Christian Bale|Steve Carell|Ryan Gosling|Brad ...,Adam McKay,This is a true story.,130,Comedy|Drama,2015-12-11,2015
25,150000000,682330139,532330139,Mission: Impossible - Rogue Nation,Tom Cruise|Jeremy Renner|Simon Pegg|Rebecca Fe...,Christopher McQuarrie,Desperate Times. Desperate Measures.,131,Action,2015-07-23,2015
26,68000000,215863606,147863606,Ted 2,Mark Wahlberg|Seth MacFarlane|Amanda Seyfried|...,Seth MacFarlane,"Ted is Coming, Again.",115,Comedy,2015-06-25,2015
27,81000000,403802136,322802136,Kingsman: The Secret Service,Taron Egerton|Colin Firth|Samuel L. Jackson|Mi...,Matthew Vaughn,Manners maketh man.,130,Crime|Comedy|Action|Adventure,2015-01-24,2015
28,20000000,88346473,68346473,Spotlight,Mark Ruffalo|Michael Keaton|Rachel McAdams|Lie...,Tom McCarthy,Break the story. Break the silence.,128,Drama|Thriller|History,2015-11-06,2015
29,61000000,311256926,250256926,Maze Runner: The Scorch Trials,Dylan O'Brien|Kaya Scodelario|Thomas Brodie-Sa...,Wes Ball,The Maze Was Just the Beginning.,132,Action|Science Fiction|Thriller,2015-09-09,2015
31,49000000,102069268,53069268,Chappie,Sharlto Copley|Dev Patel|Ninja|Yolandi Visser|...,Neill Blomkamp,I am consciousness. I am alive. I am Chappie.,120,Crime|Action|Science Fiction,2015-03-04,2015
32,29000000,287506194,258506194,Pitch Perfect 2,Anna Kendrick|Rebel Wilson|Hailee Steinfeld|Br...,Elizabeth Banks,We're back pitches,115,Comedy|Music,2015-05-07,2015
33,40000000,162610473,122610473,Bridge of Spies,Tom Hanks|Mark Rylance|Amy Ryan|Alan Alda|Seba...,Steven Spielberg,"In the shadow of war, one man showed the world...",141,Thriller|Drama,2015-10-15,2015
...,...,...,...,...,...,...,...,...,...,...,...
10482,14000000,82424789,68424789,The Great Mouse Detective,Barrie Ingham|Val Bettin|Vincent Price|Susanne...,Ron Clements|Burny Mattinson|David Michener|Jo...,London's crime-fighting ace on his most baffli...,74,Animation,1986-07-02,1986
10487,24000000,133000000,109000000,Star Trek IV: The Voyage Home,William Shatner|Leonard Nimoy|DeForest Kelley|...,Leonard Nimoy,The key to saving the future can only be found...,119,Science Fiction|Adventure,1986-11-25,1986
10491,20000000,77200000,57200000,The Name of the Rose,Sean Connery|Christian Slater|Helmut Qualtinge...,Jean-Jacques Annaud,"Who, in the name of God, is getting away with ...",130,Drama|Thriller|Mystery,1986-09-24,1986
10495,113,115103979,115103866,"The Karate Kid, Part II",Ralph Macchio|Pat Morita|Martin Kove|Charlie T...,John G. Avildsen,"This time, the combat is real.",113,Adventure|Drama|Action|Romance|Family,1986-06-18,1986
10499,5000000,328203506,323203506,Crocodile Dundee,Paul Hogan|Linda Kozlowski|Mark Blum|David Gul...,Peter Faiman,There's a little of him in all of us.,97,Adventure|Comedy,1986-09-26,1986
10501,25000000,79817939,54817939,The Golden Child,Eddie Murphy|Charles Dance|Charlotte Lewis|Vic...,Michael Ritchie,Eddie Murphy is the chosen one.,94,Action|Adventure|Comedy,1986-12-12,1986
10502,0,71624879,71624879,Ruthless People,Danny DeVito|Bette Midler|Judge Reinhold|Helen...,Jim Abrahams|David Zucker|Jerry Zucker,Sam Stone's wife has just been kidnapped... An...,93,Comedy,1986-06-26,1986
10542,0,91258000,91258000,Back to School,Rodney Dangerfield|Keith Gordon|William Zabka|...,Alan Metter,"Registration starts Friday, June 13, at theate...",96,Comedy,1986-06-13,1986
10594,8000000,441306145,433306145,The Exorcist,Linda Blair|Max von Sydow|Ellen Burstyn|Jason ...,William Friedkin,Something almost beyond comprehension is happe...,122,Drama|Horror|Thriller,1973-12-26,1973
10595,7000000,161777836,154777836,Live and Let Die,Roger Moore|Yaphet Kotto|Jane Seymour|Clifton ...,Guy Hamilton,Roger Moore is James Bond.,121,Adventure|Action|Thriller,1973-07-05,1973
10597,850000,90000000,89150000,Enter the Dragon,Bruce Lee|Jim Kelly|John Saxon|Ahna Capri|Sek Kin,Robert Clouse,Their deadly mission: to crack the forbidden i...,99,Crime|Thriller|Action,1973-08-17,1973
10601,5500000,159616327,154116327,The Sting,Paul Newman|Robert Redford|Robert Shaw|Charles...,George Roy Hill,...all it takes is a little Confidence.,129,Comedy|Crime|Drama,1973-12-25,1973
10606,777000,115000000,114223000,American Graffiti,Richard Dreyfuss|Ron Howard|Paul Le Mat|Charle...,George Lucas,Where were you in '62?,110,Comedy|Drama,1973-08-01,1973
10648,4000000,55675257,51675257,The Aristocats,Phil Harris|Sterling Holloway|Scatman Crothers...,Wolfgang Reitherman,A tune-filled animated extravaganza.,78,Animation|Comedy|Family|Adventure,1970-12-24,1970
10650,3500000,81600000,78100000,MASH,Donald Sutherland|Elliott Gould|Tom Skerritt|S...,Robert Altman,M*A*S*H Gives A D*A*M*N.,116,Comedy|Drama|War,1970-01-24,1970
10653,12000000,89800000,77800000,Patton,George C. Scott|Karl Malden|Stephen Young|Mich...,Franklin J. Schaffner,The Rebel Warrior,172,Drama|History|War,1970-01-25,1970
10654,2200000,136400000,134200000,Love Story,Ali MacGraw|Ryan O'Neal|John Marley|Ray Millan...,Arthur Hiller,NaN,99,Drama|Romance,1970-12-16,1970
10660,10000000,100489151,90489151,Airport,Burt Lancaster|Dean Martin|Jean Seberg|Jacquel...,George Seaton,The #1 novel of the year - now a motion picture!,137,Action|Drama|Thriller,1970-03-05,1970
10689,11000000,141195658,130195658,Thunderball,Sean Connery|Claudine Auger|Adolfo Celi|Lucian...,Terence Young,Look up! Look down! Look out!,130,Adventure|Action|Thriller,2065-12-16,1965
10690,8200000,163214286,155014286,The Sound of Music,Julie Andrews|Christopher Plummer|Eleanor Park...,Robert Wise,The happiest sound in all the world!,174,Drama|Family|Music|Romance,2065-03-02,1965
10691,14000000,111721910,97721910,Doctor Zhivago,Omar Sharif|Julie Christie|Geraldine Chaplin|R...,David Lean,Turbulent were the times and fiery was the lov...,197,Drama|Romance|War,2065-12-22,1965
10724,7000000,81974493,74974493,On Her Majesty's Secret Service,George Lazenby|Diana Rigg|Telly Savalas|Gabrie...,Peter R. Hunt,Far up! Far out! Far more! James Bond 007 is b...,142,Adventure|Action|Thriller,2069-12-12,1969
10725,6000000,102308889,96308889,Butch Cassidy and the Sundance Kid,Paul Newman|Robert Redford|Katharine Ross|Stro...,George Roy Hill,"Not that it matters, but most of it is true.",110,History|Drama|Western|Crime,2069-09-23,1969
10755,6000000,181813770,175813770,Grease,John Travolta|Olivia Newton-John|Stockard Chan...,Randal Kleiser,Grease is the word,110,Music,1978-07-07,1978
10756,20000000,187884007,167884007,Jaws 2,Roy Scheider|Lorraine Gary|Murray Hamilton|Jos...,Jeannot Szwarc,Just when you thought it was safe to go back i...,116,Horror|Thriller,1978-06-16,1978
10757,650000,55000000,54350000,Dawn of the Dead,David Emge|Ken Foree|Scott H. Reiniger|Gaylen ...,George A. Romero,"When there's no more room in hell, the dead wi...",127,Horror,1978-09-02,1978
10758,55000000,300218018,245218018,Superman,Marlon Brando|Gene Hackman|Christopher Reeve|N...,Richard Donner,You'll Believe a Man Can Fly!,143,Adventure|Fantasy|Action|Science Fiction,1978-12-14,1978
10759,300000,70000000,69700000,Halloween,Donald Pleasence|Jamie Lee Curtis|P.J. Soles|N...,John Carpenter,The Night HE Came Home!,91,Horror|Thriller,1978-10-25,1978
10760,2700000,141000000,138300000,Animal House,John Belushi|Tim Matheson|John Vernon|Verna Bl...,John Landis,It was the Deltas against the rules... the rul...,109,Comedy,1978-07-27,1978
10819,0,78000000,78000000,Hooper,Burt Reynolds|Robert Klein|Adam West|Jan-Micha...,Hal Needham,The greatest stuntman alive!,107,Action|Comedy,1978-07-28,1978

In [43]:
profitmovies.shape #1427 have prfit above 50 corore

(1427, 11)

In [45]:
avgruntimeprofitmovie=profitmovies["runtime"].mean() #average run time of movie above 50 crore
avgruntimeprofitmovie

113.56762438682551

In [48]:
avgbudgetprofitmovie=profitmovies["budget($)"].mean() #average budget of movie above 50 crore
avgbudgetprofitmovie

56675090.037841626

In [49]:
avgrevenueprofitmovie=data["revenue($)"].mean() #average revenue of movie above 50 crore
avgrevenueprofitmovie

39823319.79339223